name       : flickcurl
version    : 1.26
release    : 1
source     :
    - http://download.dajobe.org/flickcurl/flickcurl-1.26.tar.gz : ff42a36c7c1c7d368246f6bc9b7d792ed298348e5f0f5d432e49f6803562f5a3
license    :
    - GPL-2.0+
    - LGPL-2.1+
    - Apache-2.0+
summary    : Flickcurl - Flickr API
description: |
    Flickcurl is a C library for the Flickr API, handling creating the requests, signing, token management, calling the API, marshalling request parameters and decoding responses. It uses libcurl to call the REST web service and libxml2 to manipulate the XML responses. Flickcurl supports all of the API (see Flickcurl API coverage for details) including the functions for photo/video uploading, browsing, searching, adding and editing comments, groups, notes, photosets, categories, activity, blogs, favorites, places, tags, machine tags, institutions, pandas and photo/video metadata. It also includes a program flickrdf to turn photo metadata, tags, machine tags and places into an RDF triples description.
builddeps  :
    - pkgconfig(libxml-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
